name: Publish image on ghcr.io

on:
    schedule:
        - cron: '0 0 1 * *'
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                scheme: [humdrum, humlib]
        env:
            SCHEME: ${{ matrix.scheme }}
        steps:
            -
                name: Configure SSH
                run: |
                    mkdir -p ~/.ssh/
                    ssh-keygen -t ed25519 -f ~/.ssh/id_ed25519
                    cat >>~/.ssh/config <<END
                    Host *
                        IdentityFile ~/.ssh/id_ed25519
                        StrictHostKeyChecking no
                    END
            -
                name: Check SSH connection to github.com
                run: ssh -T git@github.com
            -
                uses: actions/checkout@v2
            -
                name: Clone humdrum-tools
                run: |
                    git clone git@github.com:humdrum-tools/humdrum-tools.git
                    (cd humdrum-tools && git submodule update --init --recursive)
            -
                name: Clone humlib
                run: git clone git@github.com:craigsapp/humlib.git
                if: "matrix.scheme == 'humlib'"
            -
                name: Build
                run: docker build -t $SCHEME -f docker/$SCHEME/Dockerfile .
            -
                name: Deploy
                run: |
                    TAG="ghcr.io/WolfgangDrescher/$SCHEME"
                    VERSION="$(date "+%Y%m%d")"
                    docker tag $SCHEME $TAG:$VERSION
                    docker tag $SCHEME $TAG:latest
                    docker images $TAG
                    echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
                    docker push $TAG:$VERSION
                    docker push $TAG:latest
