name: Publish image on Docker Hub

on:
    push:
        tags:
            - 'v*.*.*'

jobs:
    humdrum:
        runs-on: ubuntu-latest
        steps:
            -
                uses: actions/checkout@v2
            -
                name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v1
            -
                name: Docker meta
                uses: docker/metadata-action@v3
                id: meta
                with:
                    images: wolfgangdrescher/humdrum
                    tags: |
                        type=ref,event=branch
                        type=ref,event=pr
                        type=semver,pattern={{version}}
            -
                name: Login to Docker Hub
                uses: docker/login-action@v1
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}
            -
                name: Build and push
                uses: docker/build-push-action@v2
                with:
                    context: ./docker/humdrum
                    push: ${{ github.event_name != 'pull_request' }}
                    tags: ${{ steps.meta.outputs.tags }}
                    labels: ${{ steps.meta.outputs.labels }}
                    cache-from: type=registry,ref=wolfgangdrescher/humdrum:latest
                    cache-to: type=inline

    humlib:
        runs-on: ubuntu-latest
        steps:
            -
                uses: actions/checkout@v2
            -
                name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v1
            -
                name: Docker meta
                uses: docker/metadata-action@v3
                id: meta
                with:
                    images: wolfgangdrescher/humlib
                    tags: |
                        type=ref,event=branch
                        type=ref,event=pr
                        type=semver,pattern={{version}}
            -
                name: Login to Docker Hub
                uses: docker/login-action@v1
                with:
                    username: ${{ secrets.DOCKERHUB_USERNAME }}
                    password: ${{ secrets.DOCKERHUB_TOKEN }}
            -
                name: Build and push
                uses: docker/build-push-action@v2
                with:
                    context: ./docker/humlib
                    push: ${{ github.event_name != 'pull_request' }}
                    tags: ${{ steps.meta.outputs.tags }}
                    labels: ${{ steps.meta.outputs.labels }}
                    cache-from: type=registry,ref=wolfgangdrescher/humlib:latest
                    cache-to: type=inline
